"use client"
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import Nav from '../components/Nav'
import { UserProvider } from "@/context/UserContext";
import { usePathname } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentPath = usePathname()

  console.log(currentPath)

  return (
    <AuthProvider>
      <UserProvider>
        <html lang="en">
          <body className="w-screen h-screen">
            <div
              className="w-full h-full flex items-center"
            // style={{ display: 'grid', gridTemplateColumns: '1fr 3fr' }}
            >

              {
                currentPath == '/login' || currentPath == '/register' ? null : <Nav />

              }

              {children}
            </div>
          </body>
        </html>
      </UserProvider>
    </AuthProvider>
  );
}
